x = 
"BABCBBBBBBDCBABBDBDADCBCDABDDABDACAABADACDDACBBBACCDDDCDCADABAADCCDACDDCADBABACCCACDADDCACCAACCDDAACCDCCCACCDDDBCAABDDCBDCCABCABABDBBDACABAABCDACDDABABCADAADCDCCCBBCDDBDDBDDDACBADCCAAACAAABCBBBBABDCDBDDCBCCDDCAACADADABACBDDABABCBBDABCBCADCCBDDABADCABBCBDADBABBCBDDBCBACBCDABBCADADACCADCDACBBDACADAAADDBCCADBDDABAABBCCBDACBACCCBDBCACCDBDAABDCDCAADCABBCBAACDDDCAADAAACDABDCCBBDBBABDDAACBCBCCCCAADDCDDBCACADACAACADBADBBAABACACACDBCDADCBDCCBDCCCBBABCABDACADAAADBCBBCCDAACDCDACCDAAADAACBDDABCCDBACDCDBCCABBADBBBCACDABBDDAACBDBADBBBDADBBDCDDCBBDDACCBCBAABDDADCCBBBCDDACBCCAABABBBADDADBBCCABBADADBCAABCAACBCBBBCACBCBDDDACDBCDCACDAACDDBADDACBDCBCCADCDCBDCDACBDDBBDCCBABADBCAAAADBCACCDBBDCBCCCCDCCBCBACBADDDBAAACABCABBDBBAABDCCBDBACCADBDACDCACAADCABBCBDDDBACBADBDBCCBBBABCCADBACDACCBADCBDCBDCCCABACBCACCBCBCADDBADABDBBDDACCBBADDCBBACCDBACADAACDDADBBCDACDACCADCCDBDCDCDCACCACCDDCBBACADDACDADDBABCDCCACCBBCDDCBACABBBAABDACDBABABCCBCBCCBDCABCBADCDDADBCBBBCACDCACBBCCDACCCADACACDBBDBBBCBADBCAADAACCDBADCDCBACCCBDA"

x = '11AAAA222'

print(x)

n = nchar(x)

i = 1

print(n)
while (i <= n-3){
  ss = substr(x, i, i+2)
  aa = substr(x, i+3, i+3)
  print(ss)
  print(aa)
  if (ss == 'AAA' & aa != 'A'){
    print(i)
    i = i+4
  } else {
    i = i+1
  }
}
